# Generated by Django 4.2.4 on 2023-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versatile_design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
